/**
 * Bulk-inserts the global exercise library (data/exercises.json, 500+
 * entries generated by scripts/generate-exercises-json.mjs) into Neon via
 * Drizzle. Safe to re-run — existing entries are matched by name and
 * skipped rather than duplicated.
 *
 * Usage: npm run db:seed-exercises
 */
import "dotenv/config";
import { readFileSync } from "node:fs";
import { isNull } from "drizzle-orm";
import { db } from "../lib/db";
import * as schema from "../lib/db/schema";

type SeedExercise = {
  name: string;
  category: "strength" | "cardio" | "basketball" | "cycling" | "running" | "mobility";
  muscleGroups: string[];
  equipment: string | null;
  instructions: string;
};

async function main() {
  const raw = readFileSync(new URL("../data/exercises.json", import.meta.url), "utf-8");
  const seedExercises: SeedExercise[] = JSON.parse(raw);

  console.log(`Loaded ${seedExercises.length} exercises from data/exercises.json`);

  const existing = await db
    .select({ name: schema.exercises.name })
    .from(schema.exercises)
    .where(isNull(schema.exercises.userId));
  const existingNames = new Set(existing.map((e) => e.name));

  const toInsert = seedExercises.filter((e) => !existingNames.has(e.name));
  console.log(`${toInsert.length} new exercises to insert (${seedExercises.length - toInsert.length} already present)`);

  const BATCH_SIZE = 100;
  for (let i = 0; i < toInsert.length; i += BATCH_SIZE) {
    const batch = toInsert.slice(i, i + BATCH_SIZE).map((e) => ({
      name: e.name,
      category: e.category,
      muscleGroups: e.muscleGroups,
      equipment: e.equipment,
      instructions: e.instructions,
      isCustom: false,
      userId: null,
    }));
    await db.insert(schema.exercises).values(batch);
    console.log(`Inserted ${Math.min(i + BATCH_SIZE, toInsert.length)} / ${toInsert.length}`);
  }

  console.log("Done.");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
